version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:2.18.1
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data:rw
    ports:
      - "9000:9000"
      - "9443:9443"
